### ISSUE TITLE
Controller manager uses wrong volume plugin directory

### ISSUE THREAD

**Issue by qbast** [poseidon/terraform-render-bootkube#54] opened 2018-04-06 10:04 UTC
Controller manager in terraform-render-bootkube does specify volume plugin dir, so default /usr/libexec/kubernetes/kubelet-plugins/volume/exec/ is used. However Typhoon uses /var/lib/kubelet/volumeplugins everywhere.

Due to this bug, after installation of DigitalOcean storage provider, PVs cannot be mounted.

**Comment by dghubble** [comment] 2018-04-08 19:48
Kubelet having the flexvolume plugin mount was intended to enable folks to experiment with flexvolumes. Some amount of `kubectl edit` may be needed depending on the plugin. Adding this shouldn't impact those not using flexvolumes and reduces a step for experimenters. Sgtm.

**Comment by dghubble** [comment] 2018-04-08 19:49
Merged in 109ddd2dc18f87ae5baa7c740a49b2a9d7657363

**Closed by dghubble** 2018-04-08 19:49 UTC
